### ISSUE TITLE
action fails for (not yet) existing mod 

### ISSUE THREAD

**Issue by xyzzycgn** [TheBrutalX/Factorio-mod-uploader-action#17]
Tried to use your action for a new (at the moment not existing in the factorio mod-portal) mod.

Step **validate** fails with an HTTP 404:

Run TheBrutalX/factorio-mod-uploader-action@v1
  with:
    action: validate
Mod name: RLD-lang
Mod version: 1.0.0
Error: Error fetching mod info: AxiosError: Request failed with status code 404

just after merging the branch containing the publish.yml to main - opposed to your post [here](https://forums.factorio.com/viewtopic.php?f=135&t=119389), which says that tagging triggers the process.

Any idea how to procede? 

Kind regards

xyzzcgn

P.S.: I would prefer not to create the initial version of the mod manually  😉
P.P.S.: great idea to automate the publishing 👍, I am a fan of avoiding DRY

**Comment by TheBrutalX** [comment]
Hi,
the first publish it has to be done by hand, at this time I am preprinting a new version that also corrects this system.

**Comment by xyzzycgn** [comment]
Thx for your very quick  response - I like the second part of the answer much more 😉.

I definitely don't want to push - but how long do you think it will take approx to make this correction?

**Comment by TheBrutalX** [comment]
Um, I'm at work now, I'll try to do something this weekend, so between this weekend and next weekend.

**Comment by TheBrutalX** [comment]
Added to new version 1.1.1, when is tested you need only to add the mod_info.yml using this [example ](https://github.com/TheBrutalX/Factorio-Test-Mod/blob/main/mod_info.yml)

**Comment by xyzzycgn** [comment]
I'm excited about it

**Comment by xyzzycgn** [comment]
Hmm - I'm a little bit confused. What is the purpose of this YML file? It is similar in some points to the JSON object used in the finish-upload endpoint of the mod publish API, but i think it shall be a github action - isn't it?

I'll have a look on it tomorrow morning - now it's too late for me - I'm nearly 😴

**Comment by TheBrutalX** [comment]
because in addition to creating the mod in the portal it keeps the mod's information updated in the portal.

Since to update the information in the info.json file there are not all the necessary fields and I didn't want to have compatibility problems with the portal

**Comment by TheBrutalX** [comment]
Tomorrow morning I will also update the Wiki specifying the behavior, today I was too tired but I wanted to complete this change

**Comment by xyzzycgn** [comment]
In the meantime I was able to achieve some progress, but not final success.

I added a mod_info.yml to the root directory of my mod and changed version of your action to _latest_. But this fails with

```
Run TheBrutalX/factorio-mod-uploader-action@latest
file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:11
  throw Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "os" is not supported
    at file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:11:9
    at node_modules/@actions/core/lib/command.js (file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:102:27)
    at __require2 (file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:14:50)
    at node_modules/@actions/core/lib/core.js (file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:19646:21)
    at __require2 (file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:14:50)
    at file:///home/runner/work/_actions/TheBrutalX/factorio-mod-uploader-action/latest/dist/bundle.js:57125:28
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.18.0


```



The running action looks like that:


```
name: validate Factorio Mod

on:
  push:
    branches:
      - main

jobs:
  publish-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Mod
        uses: TheBrutalX/factorio-mod-uploader-action@latest
        with:
          action: validate
```

**Comment by xyzzycgn** [comment]
I've seen that you've published a new version - and it's a great step forward. Unfortunately it fails in in the final step 

![grafik](https://github.com/user-attachments/assets/a47fbd2b-94d8-4aa3-a172-70398542224f)

Strange, because I've already defined an API-Key 

![grafik](https://github.com/user-attachments/assets/7c26ef34-e3ad-4d29-99dc-a1a71ed71523)

and added it to github  

![grafik](https://github.com/user-attachments/assets/148267a3-1ff3-448e-b1e9-be726fab90e0)

a few days before

**Comment by TheBrutalX** [comment]
I've broken compatibility with a little rework, i've fixed, in 10 minute a release with a fix for that, you not need to change nothing

**Comment by TheBrutalX** [comment]
Sorry for the delay, I had some problems with the CI test

New version released

**Comment by xyzzycgn** [comment]
No problem - I know how hard it is to estimate the duration.

I think it's a step further, but the job still aborts

![grafik](https://github.com/user-attachments/assets/860ca223-4391-474e-ace8-68dc705f67c1)

May be some misconfiguration on my side - but I am not sure. Top level directory of my mod contains a file README.md and in mod_info.yml I tried to reference it like that:

```
mod_info:
  description_file: README.md
  summary: Localization for RailLogisticsDispatcher
  title: RailLogisticsDispatcher language pack
  attach_source_link: true
  license: mit
  category: localizations
  tags:
    - logistic-network
    - trains
```
