### ISSUE TITLE
Problem setting tag for mod

### ISSUE THREAD

**Issue by xyzzycgn** [TheBrutalX/Factorio-mod-uploader-action#52]
Hi,

I've been trying without success to set the "Circuit network" tag to a mod while publishing it with your github action.

My _mod_info.yml_ first looked like that:

```
mod_info:
  description_file: README.md
  summary: Save ammunition by smarter targeting
  title: D.A.R.T
  attach_source_link: true
  license: mit
  category: Content
  tags:
    - Combat
    - Circuit network
```
but that yielded

![Image](https://github.com/user-attachments/assets/8c5ef044-2526-49dc-ab79-27f87c06ac0c)

For my 2nd try I changed the tag-entries to

```
  tags:
    - combat
    - circuit-network
```

and got
![Image](https://github.com/user-attachments/assets/45c4bd12-9f10-440d-ae0f-dce0336d2bd2)

At least a little progress 😉, as I could publish the mod, but I had to set the desired tag manually in the mod portal.

Any idea, what I am doing wrong?

I suspect that your action is using the Mod details API on https://mods.factorio.com/api/v2/mods/edit_details and according to their [documentation](https://wiki.factorio.com/Mod_details_API#Tags) I would expect, that one of the two tried variants should work, doesn't it?
